/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nz_net_bishop_omega_gpio_support_GPIOSupport */

#ifndef _Included_nz_net_bishop_omega_gpio_support_GPIOSupport
#define _Included_nz_net_bishop_omega_gpio_support_GPIOSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nz_net_bishop_omega_gpio_support_GPIOSupport
 * Method:    wrapperForkSet
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nz_net_bishop_omega_gpio_support_GPIOSupport_wrapperForkSet
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     nz_net_bishop_omega_gpio_support_GPIOSupport
 * Method:    wrapperForkStop
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nz_net_bishop_omega_gpio_support_GPIOSupport_wrapperForkStop
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     nz_net_bishop_omega_gpio_support_GPIOSupport
 * Method:    wrapperForkInfo
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nz_net_bishop_omega_gpio_support_GPIOSupport_wrapperForkInfo
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     nz_net_bishop_omega_gpio_support_GPIOSupport
 * Method:    wrapperExecCommand
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nz_net_bishop_omega_gpio_support_GPIOSupport_wrapperExecCommand
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
